### ISSUE TITLE
Tempest Wind Speeds are mps in JSON but treated as mph in receiver code

### ISSUE THREAD

**Issue by MattLugar** [leoherzog/WundergroundStationForwarder#15]
Noticed that my tempest station was sending extremely low wind values... Looking at the JSON from my station, as well as the API documentation, the API returns wind in mps and not mph. 

[Tempest API Docs](https://weatherflow.github.io/Tempest/api/swagger/)

The code on the receiver needs to be adjusted to convert to mph and use mps as default...

**Comment by leoherzog** [comment]
Thanks so much! I saw the `station_units` part of the JSON response from their API, and for me, it contained `"units_wind": "mph"`, so I had made an assumption that the observations were in those units as well. Thanks for finding my oversight!
