### ISSUE TITLE
Additional Parameters for WeatherCloud

### ISSUE THREAD

**Issue by MattLugar** [leoherzog/WundergroundStationForwarder#16]
Found a few additional parameters you can pass to WeatherCloud if you wanted to add them:

Current Day Precipitation Total -> &rain
Solar Radiation -> &solarrad
Dewpoint -> &dew
Heat Index -> &heat
Wind Chill -> &chill
Wind Gust -> &wspdhi

**Comment by leoherzog** [comment]
Can't hurt! Thanks for the heads up.
