### ISSUE TITLE
Distinguish Between "Rain Over Last 24 Hours" and "Rain Since Midnight"

### ISSUE THREAD

**Issue by leoherzog** [leoherzog/WundergroundStationForwarder#18]
Update every sender and receiver to distinguish between these two values

**Comment by aolfish** [comment]
CWOP has input values showing : (rain 1hr), (rain 24hr) & (rain mn).  My weather reports only showed values under the (rain 1hr) column.

**Comment by leoherzog** [comment]
Added support to cwop.rest to distinguish the two.

https://github.com/leoherzog/cwop.rest/commit/06f74498af4cc5819ac5c95ee537845c494d21a8

https://web.archive.org/web/20230716040809/http://www.wxqa.com/faq.html item number 7

**Comment by leoherzog** [comment]
Done!

**Comment by aolfish** [comment]
Finally got a smidge of rain today.  Only 0.06 in.  My CWOP weather reports on findu.com only showing rain in 1hr column.  Nothing (0.00) in the 24hr and MN columns.  Using the V2.5.0

**Comment by leoherzog** [comment]
@aolfish What is your data source?

**Comment by aolfish** [comment]
Sorry ... Acurite

**Comment by leoherzog** [comment]
Sure. If you uncomment [the `console.log(JSON.stringify(acuriteConditions));` line in the `refreshFromMyAcurite_()` function](https://github.com/leoherzog/WundergroundStationForwarder/blob/v2.5.0/code.gs#L274), you'll start to see what data I get from them in the ☰▶ Execution Log on the left. There's a "Rainfall" one that I can grab for [the precipitation rate](https://github.com/leoherzog/WundergroundStationForwarder/blob/v2.5.0/code.gs#L325-L329), but MyAcurite doesn't give me any stats on hourly rainfall or totals over 24 hours/since midnight. Unless there's another "get historical data" API endpoint that I don't know of, I think we're out of luck. It's tough to develop for this API specifically since it's an undocumented, internal API that could change or go away at any time. Official, Acurite offers no API for MyAcurite.
