### ISSUE TITLE
no more data on Meteo sites

### ISSUE THREAD

**Issue by yo2ldk** [leoherzog/WundergroundStationForwarder#21]
Hi,
I have this error:
Problem fetching https://api.weather.com/v2/pws/observations/current?stationId=xxxxx&format=json&units=e&numericPrecision=decimal&apiKey=xxxxxxx

fetchJSON_	@ Code.gs:920
refreshFromIBM_	@ Code.gs:120
Schedule	@ Code.gs:77

something was changed ?

Thank you for all your work !!

**Comment by leoherzog** [comment]
Did you Wunderground API Key expire?

https://www.wunderground.com/member/api-keys

**Comment by yo2ldk** [comment]
Thank you for reply,  
no, not was expired, I make it anyway a new one
also Meteo station have an upload key for Wunderground and still ok
I will try it more..

**Comment by yo2ldk** [comment]
no more errors on Run
maybe it was something with my key,,
Thank you for support and this nice app!
