### ISSUE TITLE
forwarding to CWOP to other sites

### ISSUE THREAD

**Issue by CT2IRJ** [leoherzog/WundergroundStationForwarder#22]
Hi.

This is a great tool for those who like myself owns a WS wich does not provide data forwarding to CWOP.

Is there a chance that provides the opposite, I mean to grab data from CWOP stations and forward them to any other weather service?

I'll explain, i have in cooperation with AMSAT-PO a few remote weather stations that work only via APRS.
Our city hall asked us if we can feed them the data to monitor weather conditions in case of wildfires and such.

Their main goal was to create a dashboard like webpage to display the conditions.
I was thinking on the way to achieve that was to forward the specific weather stations to WU (or other service) and with the API of such service grab the data to their use...

thanks in advance

**Comment by leoherzog** [comment]
Great question. It would take some work. Lemme look into that for you to see if it's possible.

**Comment by CT2IRJ** [comment]
Hi Leo.

Thanks for considering it.


Salomão Fresco

Callsign: CT2IRJ

GRID Locator: IM59re -- CQ Zone 14 / ITU Zone 37

QTH: Fazendas de Almeirim, Portugal

**Comment by leoherzog** [comment]
Added a new datasource option for APRS (CWOP) weather stations in the latest release, [v2.6.0](https://github.com/leoherzog/WundergroundStationForwarder/releases/tag/v2.6.0). This uses the wonderful [aprs.fi API](https://aprs.fi/page/api). You'll need a free account to get an API key from them, but then yes, this script can now pull APRS reports and forward them on to all of the existing supported destinations.

**Comment by CT2IRJ** [comment]
Great work.
I'll try it when i get home.

Thanks again for your help

Salomão Fresco


Callsign: CT2IRJ

GRID Locator: IM59re -- CQ Zone 14 / ITU Zone 37
QTH: Fazendas de Almeirim, Portugal

A terça, 18/06/2024, 17:03, Leo ***@***.***> escreveu:

**Comment by CT2IRJ** [comment]
Hi again Leo,

I've tried briefly the new script, but it seems it is not working.
Maybe in the weekend (if kids allow) I'll give it another go.

Thanks

**Comment by leoherzog** [comment]
Okay. If you could describe what steps you've done and where you got stuck, I'll do my best to help.
