### ISSUE TITLE
ibm (wunderground) API keys

### ISSUE THREAD

**Issue by aolfish** [leoherzog/WundergroundStationForwarder#24]
Weather Underground has changed they API key settings.  API keys are now limited to 1500 calls per day and 30 calls per minute.

That equals 1440 Calls per day for device.
I have 2 stations reporting so my daily call is 2880, which is over the limit .  
Weather Underground suspends my key and starts failing.
I regenerate new key and it will work for couple days then repeats.

Any way to change calling from 1 minute to 2 minutes ?

**Comment by leoherzog** [comment]
Classic. Ugh.

Apps Script only lets you choose every one or five minutes :(

If you change [`Line 107`](https://github.com/leoherzog/WundergroundStationForwarder/blob/v2.6.0/code.gs#L107) in the code from:

```js
if (updateWunderground) ScriptApp.newTrigger('updateWunderground_').timeBased().everyMinutes(1).create();
```

to:

```js
if (updateWunderground) ScriptApp.newTrigger('updateWunderground_').timeBased().everyMinutes(5).create();
// options are every 1, 5, 10, 15 or 30 minutes
// https://developers.google.com/apps-script/reference/script/clock-trigger-builder#everyMinutes(Integer)
```

![Minutes-based triggers dropdown options in the menu](https://github.com/leoherzog/WundergroundStationForwarder/assets/5376265/4eda4d4d-19fd-45cf-87c0-27cefcf96394)

**Comment by leoherzog** [comment]
There are alternative ways to schedule it every 2 minutes with a watcher function that sets exact every-two-minutes triggers, but it'd add a lot of complication to the code. Sorry 'bout that.

**Comment by aolfish** [comment]
Thanks Leo. 
 May try directly from Acurite since you've updated since we first started.  That would cutdown half of my daily call.

**Comment by karss79** [comment]
@aolfish: Instead of having two devices under one wunderground account, why don't you use separate WU account for each device. By this way, you may be able to overcome the WU API call limits.

**Comment by leoherzog** [comment]
I think I'm gonna mark this issue as closed, since this is a limitation with the upstream provider and not with this project.
