### ISSUE TITLE
Add MET (UK) support 

### ISSUE THREAD

**Issue by esetleges** [leoherzog/WundergroundStationForwarder#27]
It would be nice to have MET ((WOW) support too in the script:

https://wow.metoffice.gov.uk/

https://about.metservice.com/our-company/your-weather/add-your-own-weather-station

Cheers!

**Comment by leoherzog** [comment]
Sounds cool! I'll read up on the docs.

**Comment by leoherzog** [comment]
https://wow.metoffice.gov.uk/support/dataformats#automatic

Leaving here for reference.

**Comment by leoherzog** [comment]
Released [`v2.8.0`](https://github.com/leoherzog/WundergroundStationForwarder/releases/tag/v2.8.0) just now that adds this. Thanks again for the idea!

**Comment by esetleges** [comment]
hey thanks.for the support. It seems the script runs to error with WOW:

Error	
Exception: Request failed for http://wow.metoffice.gov.uk returned code 400. Truncated server response: Bad Request (use muteHttpExceptions option to examine full response)
    at updateWOW_(Code:1053:30)


May they updating their servers ( notification on their site) or else.
