### ISSUE TITLE
error while sending data to windy and cwop

### ISSUE THREAD

**Issue by indrameshdevops** [leoherzog/WundergroundStationForwarder#28]
While sending data to windy and cwop few of the execution are getting the following error.

Exception: Request failed for https://stations.windy.com returned code 400. Truncated server response: {"update":{"update":{"stations":[],"observations":[{"si":0,"time":"2024-09-12T06:55:00.000Z","temp":33.8888916,"wind":0.8001995415,"wind_dir":105,"... (use muteHttpExceptions option to examine full response)
    at updateWindy_(Code:834:30)

Sep 12, 2024, 12:52:51 PM
Debug
https://send.cwop.rest/?id=GW5350&lat=11.4799278&long=78.1964977&time=1726124100000&tempf=93&windspeedmph=1.79&windgustmph=2.24&winddir=105&baromin=984&humidity=51&solarradiation=586.22&rainin=0&dailyrainin=0&software=appsscriptforwarderv2.7.0
Sep 12, 2024, 12:52:51 PM
Error
Exception: Request failed for https://send.cwop.rest returned code 422. Truncated server response: Timestamp in packet is not within last 5 minutes (use muteHttpExceptions option to examine full response)
    at updateCWOP_(Code:1039:30)

**Comment by indrameshdevops** [comment]
only for windy and cwop it is keep failing now.

**Comment by leoherzog** [comment]
Hmm. It sounds like your data source is not fresh. Which service are you pulling data _from_?

**Comment by indrameshdevops** [comment]
Hi, 

Thank for the reply. at this moment after 3 to 4 hrs. windy and cwop also getting update. I am uploading from Ambient. 

Reg of the senders are working fine.

**Comment by leoherzog** [comment]
I suspect that you had an outage with your datasource and the data wasn't fresh. cwop.rest is [written](https://github.com/leoherzog/cwop.rest/blob/51a673dd63646c874ba0ac9f3f7c0da757fadfb5/send-cwop-rest.js#L234-L248) in such a way where it rejects measurements that are old, since readings that are submitted to CWOP are supposed to be at that moment. Keep us posted if it happens again!

**Comment by indrameshdevops** [comment]
ok , looks good now.  uploading is happening fine. seems we need to wait for 2 to 3 hrs . 

Thanks again for checking.
