### ISSUE TITLE
WOW: Error - 400

### ISSUE THREAD

**Issue by esetleges** [leoherzog/WundergroundStationForwarder#30]
hey thanks for the support. It seems the script runs to an error with WOW:

Error	
Exception: Request failed for http://wow.metoffice.gov.uk returned code 400. Truncated server response: Bad Request (use muteHttpExceptions option to examine full response)
    at updateWOW_(Code:1053:30)

May they updating their servers ( notification on their site) or else.

_Originally posted by @esetleges in https://github.com/leoherzog/WundergroundStationForwarder/issues/27#issuecomment-2374772587_

**Comment by esetleges** [comment]
ok, I messed up user id with station id - disadvantage of using on phone

**Comment by leoherzog** [comment]
Neato. Glad you got it working.
