### ISSUE TITLE
Help me I know nothing

### ISSUE THREAD

**Issue by Hero21b** [leoherzog/WundergroundStationForwarder#34]
Here is my error message:

Error	
Problem fetching https://swd.weatherflow.com/swd/rest/observations/station/xxxxx?token=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
fetchJSON_	@ Code.gs:1192
refreshFromWeatherflow_	@ Code.gs:477
Schedule	@ Code.gs:102

The only edits I have made are to my Wunderground API + Station ID, and to  updateWindy = true and the Windy API Key. I am useless with coding

![1](https://github.com/user-attachments/assets/37174fa8-f248-4bc3-9a19-f4c1ab04a6a1)
![2](https://github.com/user-attachments/assets/d749c584-993b-42db-8560-aebecc3f89ae)

**Comment by Hero21b** [comment]
Nevermind, I see that I needed to update weatherflow to ibm on line 10. I guess I'm not fully useless, just slow lol.

**Comment by leoherzog** [comment]
Are you trying to pull station readings from Wunderground and send them only to windy.com? If so, you'll also need to change line 10 to

```js
const datasource = 'ibm';
```

As you have it now, it's still trying to pull readings from Weatherflow, which is a different weather station brand.

**Comment by Hero21b** [comment]
Thanks. The reason I want to use this is that I have an Ecowitt station which can't send directly to Windy. Thanks so much for building this!

**Comment by leoherzog** [comment]
Sure thing! Looks like we commented at the same time 😅 have a good open
