### ISSUE TITLE
WindGust is missing for PWSWeather

### ISSUE THREAD

**Issue by judgetom** [leoherzog/WundergroundStationForwarder#4]
Hello,

in the function updatePWSWeather_() the following line is missing:
  _if (station.imperial.windGust != null) request += '&windgustmph=' + station.imperial.windGust;_

By adding this line the windGust will also be provided.

Best regards, and thanks for the script,
judgetom

**Comment by leoherzog** [comment]
Thanks! I was basing this built URL off of the PWSWeather uploader in `acuparse`.

https://gitlab.com/acuparse/acuparse/-/blob/dev/src/fcn/cron/uploaders/pwsweather.php

Is this parameter actually supported by PWSWeather? They don't have any API docs :(

**Comment by leoherzog** [comment]
Seems to be referenced by other projects!

https://github.com/OurColonial/WeatherLink-to-PWSweather

https://pywws.readthedocs.io/en/latest/api/pywws.service.pwsweather.html

**Comment by judgetom** [comment]
Yes, it works well since I added it.

**Comment by leoherzog** [comment]
Thanks again!
