### ISSUE TITLE
Upload to Wunderground failed after script update to v2.9.0

### ISSUE THREAD

**Issue by chiefcomm** [leoherzog/WundergroundStationForwarder#40]
Hi All, hopefully someone can point out my error.  I've been using the script for so long I can't remember and today I decided to update the script to the latest v2.9.0.

Since updating to v2.9.0 I have the following error in logs uploading to Wunderground (uploading to PWSWeather is OK).

![image](https://github.com/user-attachments/assets/c89dbba4-c041-4096-b7b5-803d835bc85e)

Any clues? - I checked the Station ID and Key which have remained unchanged in years.

**Comment by chiefcomm** [comment]
Ignore this I linked WeatherFlow to Wunderground via the native WeatherFlow integration.

**Comment by leoherzog** [comment]
Hmm. If you were updating from 1.x.x, some of the variable names at the top of the document might have changed. Make sure that the Lines [10-73](https://github.com/leoherzog/WundergroundStationForwarder/blob/v2.9.0/code.gs#L10-L73) don't have any missing or misnamed variables!
