### ISSUE TITLE
Error message - "latestRelease is not defined"

### ISSUE THREAD

**Issue by f2mbsb** [leoherzog/WundergroundStationForwarder#5]
Hi @leoherzog!
Congrats on the new features! 
I am facing an error message during execution of v1.1.3, as attached.
Thanks.
![error](https://user-images.githubusercontent.com/54805983/115928633-d73d5700-a45c-11eb-9cf4-69d67fb27abd.png)

**Comment by leoherzog** [comment]
Found it! Thank you!
