### ISSUE TITLE
Wrong unit for weathercloud barometric pressure 

### ISSUE THREAD

**Issue by biuklija** [leoherzog/WundergroundStationForwarder#7]
Barometric pressure is not logged for weathercloud.net because the unit is wrong. 
`if (station.imperial.pressure != null) request += '&**baromin**=' + (new Number(station.imperial.pressure).**inhgTohPa**() * 10).toFixedNumber(0);`
The argument in line 125 should be "bar" instead of "baromin".

**Comment by leoherzog** [comment]
Ah! Thank you so much! I'll update that now.
